# Generated by Django 5.2.13 on 2026-08-31 10:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=64, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('role', models.CharField(choices=[('student', 'Student'), ('supervisor', 'Supervisor'), ('hod', 'Head of Department'), ('committee', 'Committee Member'), ('admin', 'Administrator')], db_index=True, default='student', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('title', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('enrollment_year', models.PositiveIntegerField(blank=True, null=True)),
                ('program', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('student_id',),
            },
        ),
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('max_students', models.PositiveIntegerField(blank=True, help_text='Leave empty to use the department default.', null=True)),
                ('is_accepting_students', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
