# Generated by Django 5.0.9 on 2026-08-31 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentpolicy',
            name='similarity_threshold',
            field=models.PositiveIntegerField(default=60, help_text='Percent similarity above which a topic is flagged as a possible duplicate.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
