# Generated by Django 5.2.13 on 2026-08-31 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monographs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('result', models.CharField(blank=True, choices=[('passed', 'Passed'), ('passed_with_revisions', 'Passed With Minor Revisions'), ('failed', 'Failed')], db_index=True, max_length=32)),
                ('held_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('required_revisions', models.TextField(blank=True)),
                ('revisions_due_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('monograph', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defense', to='monographs.monograph')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-scheduled_at',),
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('chair', 'Chair'), ('supervisor', 'Supervisor'), ('internal', 'Internal Examiner'), ('external', 'External Examiner'), ('secretary', 'Secretary')], default='internal', max_length=32)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comments', models.TextField(blank=True)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('has_read_monograph', models.BooleanField(default=False)),
                ('attended', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='committee_seats', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('defense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee', to='defenses.defense')),
            ],
            options={
                'ordering': ('role', 'member__full_name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('defense', 'member'), name='unique_member_per_defense')],
            },
        ),
    ]
