# Generated by Django 5.2.13 on 2026-08-31 10:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monograph',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('objectives', models.TextField(blank=True)),
                ('methodology', models.TextField(blank=True)),
                ('expected_outcome', models.TextField(blank=True)),
                ('supervisor_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('topic_submitted', 'Topic Submitted'), ('topic_approved', 'Topic Approved'), ('proposal_submitted', 'Proposal Submitted'), ('under_review', 'Under Review'), ('revision_required', 'Revision Required'), ('proposal_approved', 'Proposal Approved'), ('research_in_progress', 'Research In Progress'), ('final_submission', 'Final Submission'), ('final_review', 'Final Review'), ('defense_scheduled', 'Defense Scheduled'), ('defended', 'Defended'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=32)),
                ('stage_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closure_reason', models.TextField(blank=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monographs', to='organization.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monographs', to='organization.department')),
                ('research_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monographs', to='organization.researcharea')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_monographs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('monograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='monographs.monograph')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MonographMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_lead', models.BooleanField(default=False, help_text='The student who submits on behalf of the group.')),
                ('contribution', models.TextField(blank=True, help_text='Which part of the work this student is responsible for.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('monograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='monographs.monograph')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monograph_memberships', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_lead', 'student__full_name'),
            },
        ),
        migrations.CreateModel(
            name='StageTransition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('from_stage', models.CharField(blank=True, max_length=32)),
                ('to_stage', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True)),
                ('days_in_previous_stage', models.PositiveIntegerField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('monograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='monographs.monograph')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TopicApprovalVote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField()),
                ('comment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('monograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_votes', to='monographs.monograph')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='monograph',
            index=models.Index(fields=['department', 'academic_year', 'stage'], name='monographs__departm_4c1bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='monograph',
            index=models.Index(fields=['supervisor', 'stage'], name='monographs__supervi_1c3428_idx'),
        ),
        migrations.AddIndex(
            model_name='monograph',
            index=models.Index(fields=['stage', 'stage_changed_at'], name='monographs__stage_7eecd4_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['monograph', '-created_at'], name='monographs__monogra_dfb935_idx'),
        ),
        migrations.AddConstraint(
            model_name='monographmember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('monograph', 'student'), name='unique_student_per_monograph'),
        ),
        migrations.AddIndex(
            model_name='stagetransition',
            index=models.Index(fields=['monograph', 'created_at'], name='monographs__monogra_98f149_idx'),
        ),
        migrations.AddConstraint(
            model_name='topicapprovalvote',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('monograph', 'voter'), name='unique_vote_per_voter'),
        ),
    ]
