# Generated by Django 5.0.9 on 2026-08-31 11:19

import django.core.files.storage
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(location='/home/musawer-hashimi/Projects/MMIS/backend/private_media'), upload_to=documents.models.upload_path, validators=[documents.models.validate_upload]),
        ),
    ]
