# Generated by Django 5.2.13 on 2026-08-31 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('monographs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('abstract', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('author_names', models.JSONField(blank=True, default=list)),
                ('supervisor_name', models.CharField(blank=True, max_length=255)),
                ('department_name', models.CharField(blank=True, max_length=255)),
                ('academic_year_name', models.CharField(blank=True, max_length=64)),
                ('research_area_name', models.CharField(blank=True, max_length=255)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('defended_on', models.DateField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('final_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentversion')),
                ('monograph', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='archive_entry', to='monographs.monograph')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'archive entries',
                'ordering': ('-defended_on', 'title'),
                'indexes': [models.Index(fields=['department_name', 'academic_year_name'], name='archive_arc_departm_51a525_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopicSimilarity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(help_text='Percent similarity, 0 to 100.')),
                ('matched_terms', models.JSONField(blank=True, default=list)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_reason', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('monograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='monographs.monograph')),
                ('similar_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_by', to='monographs.monograph')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'topic similarities',
                'ordering': ('-score',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('monograph', 'similar_to'), name='unique_similarity_pair')],
            },
        ),
    ]
